/* Copyright (C) 2025 EchoStretch

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3, or (at your option) any
later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; see the file COPYING. If not, see
<http://www.gnu.org/licenses/>.  */

#ifndef SELF_STORE_H
#define SELF_STORE_H

#include <stddef.h>

/* A payload sent over the network exists in memory only: there is no file
   to hand to a payload manager. So the build embeds a copy of the ELF - the
   same program, built one step earlier without this blob. A copy started
   from that stored file has nothing embedded, and needs nothing: it is
   stored already. Generated by the Makefile; empty in a plain build. */
extern const unsigned char self_elf[];
extern const size_t        self_elf_len;

/* 1 when this copy carries an ELF it can store. */
int self_store_available(void);

/* Uploads the embedded ELF to pldmgr on this console under DUMPER_ELF_NAME,
   replacing a file of that name. Returns 0 on success, -1 with a reason a
   user can act on in err. */
int self_store_to_pldmgr(char *err, size_t err_size);

#endif /* SELF_STORE_H */
