# Klog Viewer - the second web homebrew on webhb/. See README.md.
WHB_ROOT    := ../..
WHB_APP     := klogview
WHB_PAGE    := web/index.html
WHB_ICON    := assets/icon0.png
WHB_SOURCES := main.c

include $(WHB_ROOT)/webhb/webhb.mk
